apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app
  description: my first app
  annotations:
    github.com/project-slug: odirleyrp/python_app
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental