apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: my-app
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: odirleyrp/python-app:846e6b44e7ff5957ebdea60c269896bfef2602bf
        ports:
        - containerPort: 5000
